#!/usr/bin/env php
<?php

declare(strict_types=1);

use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Application;
use Whoops\Run as WhoopsRun;

$bootstrap = require __DIR__ . '/config/bootstrap.php';

/** @var ContainerInterface $container */
$container = $bootstrap();

$app = $container->get(Application::class);

// Use Whoops to catch the exception
if (class_exists(WhoopsRun::class)) {
    $app->setCatchExceptions(false);
}

$app->add($container->get(\Config\SetupDockerDatabase::class));

$directory = new RecursiveDirectoryIterator(__DIR__ . '/src/Cli');
$iterator = new RecursiveIteratorIterator($directory);
$finalIterator = new RegexIterator(
    $iterator,
    '/^.+\.php$/i',
    RecursiveRegexIterator::GET_MATCH
);

$dir = __DIR__ . '/src';
$dirArray = explode('/', $dir);

foreach ($finalIterator as $files) {
    foreach ($files as $file) {
        $baseName = basename($file, '.php');
        $fileNameArray = explode('/', $file);
        $newFileNameArray = array_slice($fileNameArray, count($dirArray));
        unset($newFileNameArray[count($newFileNameArray) - 1]);
        $className = implode('\\', $newFileNameArray);
        $className = '\App\\' . $className . '\\' . $baseName;
        $command = $container->get($className);
        $app->add($command);
    }
}

/** @noinspection PhpUnhandledExceptionInspection */
$app->run();
