version: '3.7'

services:
  web:
    env_file: .env
    build:
      context: ./docker/web
    container_name: buzzingpixel-web
    environment:
      HOSTNAME: buzzingpixel-web
    volumes:
      - .:/opt/project:delegated
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/nginx.conf

  php:
    env_file: .env
    build:
      context: ./docker/php
    container_name: buzzingpixel-php
    environment:
      HOSTNAME: buzzingpixel-php
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - .:/opt/project:delegated
      - composer-home-volume:/composer-home-volume

  db:
    env_file: .env
    build:
      context: ./docker/db
    container_name: buzzingpixel-db
    environment:
      HOSTNAME: buzzingpixel-db
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  composer-home-volume:
  db-volume:
  yarn-cache-volume:
