version: '3.7'

services:
  web:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: buzzingpixel-web
    ports:
      - 26087:26087
    environment:
      HOSTNAME: buzzingpixel-web
    networks:
      default:
        aliases:
          - buzzingpixel.localtest.me
          - buzzingpixel.com
          - www.buzzingpixel.app

  php:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: buzzingpixel-php
    environment:
      HOSTNAME: buzzingpixel-php
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - composer-home-volume:/composer-home-volume
    networks:
      default:
        aliases:
          - buzzingpixel-php

  db:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    container_name: buzzingpixel-db
    environment:
      HOSTNAME: buzzingpixel-db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 18974:5432
    networks:
      default:
        aliases:
          - buzzingpixel-db

volumes:
  composer-home-volume:
  db-volume:

networks:
  default:
    external:
      name: proxy
