version: '3.7'

services:
  web:
    build:
      context: ./docker/web
    container_name: buzzingpixel-web
    environment:
      HOSTNAME: buzzingpixel-web
      COMPOSER_HOME: /composer-home-volume
      NGINX_HOST: foobar.com
      NGINX_PORT: 80
    ports:
      - 26087:443
    volumes:
      - .:/app:delegated
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      common-buzzingpixel-network:
        aliases:
          - buzzingpixel.localtest.me
  php:
    build:
      context: ./docker/php
    container_name: buzzingpixel-php
    environment:
      HOSTNAME: buzzingpixel-php
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - .:/app:delegated
      - composer-home-volume:/composer-home-volume:delegated
    networks:
      common-buzzingpixel-network:
  db:
    build:
      context: ./docker/db
    container_name: buzzingpixel-db
    environment:
      HOSTNAME: buzzingpixel-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 18974:3306
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      common-buzzingpixel-network:

volumes:
  composer-home-volume:
  db-volume:

networks:
  common-buzzingpixel-network:
