version: '3.7'

services:
  web:
    ports:
      - 26087:443

  php:
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 18974:5432
