title: Compatibility

content:
  - type: heading
    level: 3
    content: Field Type Contexts

  - type: content
    content: |
      Ansel is compatible with the following contexts, and regardless of the context uses the same settings presented as uniformly as possible.

      - [Channel Entries](https://docs.expressionengine.com/latest/control-panel/entry-manager.html)
      - [Fluid Field (EE 4+)](https://docs.expressionengine.com/latest/fieldtypes/fluid.html#fluid-fieldtype)
      - [Grid](https://docs.expressionengine.com/latest/fieldtypes/grid.html)
      - [Bloqs](https://eebloqs.com/)
      - [Low Variables](http://gotolow.com/addons/low-variables)

  - type: heading
    level: 3
    content: Storage Locations

  - type: content
    content: |
      Ansel is also compatible with more than one storage location type.

      - [ExpressionEngine File Locations](https://docs.expressionengine.com/latest/cp/files/index.html)
      - [Treasury](/software/treasury)
      - [Assets](https://eeharbor.com/assets)

  - type: image
    1x: /content-images/ansel-ee/ansel-field-options.png
    2x: /content-images/ansel-ee/ansel-field-options-2x.png
    alt: Ansel Field Options
