title: Configuring

content:
  - type: content
    content: Ansel has a few settings you may want to look at before diving in to making your Ansel fields.

  - type: image
    1x: /content-images/ansel-ee/ansel-global-settings.png
    2x: /content-images/ansel-ee/ansel-global-settings-2x.png
    alt: Ansel Global Settings

  - type: heading
    level: 3
    content: License Key

  - type: content
    content: |
      - The first thing you will want to do is visit the License page and enter your license key from your purchase.

        The license page can by located by clicking on "Ansel" from the list of Add-ons in the Add-on Manager, then clicking on the "License" link in the sidebar.

  - type: note
    heading: Remember
    content: You will need a license for each of the sites/public domain names you install Ansel on.

  - type: heading
    level: 3
    content: Global Settings

  - type: content
    content: Ansel has a number of other global settings you may wish to take advantage of. To access them, click on "Ansel" from the list of Add-ons in the Add-on Manager

  - type: note
    content: The following settings have config file overrides which you can use to keep your config in your config file.

  - type: heading
    level: 4
    content: Default host

  - type: content
    content: |
      This field is blank on new installs. If you wish all image URLs to be served from a CDN (for instance), you can enter a fully qualified URL here.

      The config override item is `$config['ansel']['default_host']`.

  - type: heading
    level: 4
    content: Hide the Upload/Save directory instructions when setting up a new field?

  - type: content
    content: |
      Hide the instructions for how to use the Upload/Save directory settings when setting up/editing Ansel fields.

      The config override item is `$config['ansel']['hide_source_save_instructions'] = true;`.

  - type: heading
    level: 4
    content: Default maximum quantity

  - type: content
    content: |
      Use this to set a default value for maximum quantity when creating new fields.

      The config override item is `$config['ansel']['default_max_qty']`.

  - type: heading
    level: 4
    content: Default image quality

  - type: content
    content: |
      Use this to set a default value for the image quality setting when creating new fields.

      The config override item is `$config['ansel']['default_image_quality']`.

  - type: heading
    level: 4
    content: Default force JPG setting

  - type: content
    content: |
      Use this to set newly created fields to default to forcing JPG.

      The config override item is `$config['ansel']['default_jpg']`.

  - type: heading
    level: 4
    content: Default retina mode

  - type: content
    content: |
      Use this to set newly created fields to default to retina mode.

      The config override item is `$config['ansel']['default_retina']`.

  - type: heading
    level: 4
    content: Default display title field

  - type: content
    content: |
      Use this to set newly created fields to default to show the title field.

      The config override item is $config['ansel']['default_show_title'].

  - type: heading
    level: 4
    content: Default require title

  - type: content
    content: |
      Use this to set newly created fields to default to require the title field.

      The config override item is `$config['ansel']['default_require_title']`.

  - type: heading
    level: 4
    content: Default customize title label

  - type: content
    content: |
      Use this to set newly created fields to have a default value for the title label.

      The config override item is `$config['ansel']['default_title_label']`.

  - type: heading
    level: 4
    content: Default display caption field

  - type: content
    content: |
      Use this to set newly created fields to default to show the caption field.

      The config override item is `$config['ansel']['default_show_caption']`.

  - type: heading
    level: 4
    content: Default require caption

  - type: content
    content: |
      Use this to set newly created fields to default to require the caption field.

      The config override item is `$config['ansel']['default_require_caption']`.

  - type: heading
    level: 4
    content: Default customize caption label

  - type: content
    content: |
      Use this to set newly created fields to have a default value for the caption label.

      The config override item is `$config['ansel']['default_caption_label']`.

  - type: heading
    level: 4
    content: Default display cover field

  - type: content
    content: |
      Use this to set newly created fields to default to show the cover field.

      The config override item is `$config['ansel']['default_show_cover']`.

  - type: heading
    level: 4
    content: Default require cover

  - type: content
    content: |
      Use this to set newly created fields to default to require the cover field.

      The config override item is `$config['ansel']['default_require_cover']`.

  - type: heading
    level: 4
    content: Default customize cover label

  - type: content
    content: |
      Use this to set newly created fields to have a default value for the cover label.

      The config override item is `$config['ansel']['default_cover_label']`.

  - type: heading
    level: 3
    content: Config file only options

  - type: content
    content: There are a couple of configuration options that can only be set in the config file.

  - type: heading
    level: 4
    content: "`optimizerShowErrors`"

  - type: content
    content: |
      Normally the optimizer for `jpegoptim`, `gifsicle`, and `optipng` will fail silently. However, it can sometimes be useful to know if something is going wrong — for instance, when you install the tools on your server and want to make sure they are working. If the optimizer is not able to find the tools or they return an error code when trying to optimize the image, when this config setting is set to true, the optimizer will throw an error for you to see.

      `$config['ansel']['optimizerShowErrors'] = true;`

  - type: heading
    level: 4
    content: "`disableOptipng`"

  - type: content
    content: |
      Disables optipng optimization.

      `$config['ansel']['disableOptipng'] = true;`

  - type: heading
    level: 4
    content: "`disableJpegoptim`"

  - type: content
    content: |
      Disables jpegoptim optimization.

      `$config['ansel']['disableJpegoptim'] = true;`

  - type: heading
    level: 4
    content: "`disableGifsicle`"

  - type: content
    content: |
      Disables gifsicle optimization.

      `$config['ansel']['disableGifsicle'] = true;`

  - type: heading
    level: 4
    content: "`forceGD`"

  - type: content
    content: |
      Forces Ansel to use [GD](http://php.net/manual/en/book.image.php) image processing for manipulating images. Normally, Ansel will auto-detect if [ImageMagick](https://www.imagemagick.org/) is installed/setup with PHP and use it for manipulating images. If for whatever reason you would like to force Ansel to use GD even though ImageMagick is available, make this setting true.

      `$config['ansel']['forceGD'] = true;`
