name: ESLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run Yarn Install
        run: yarn

      - name: Run ESLint
        run: node_modules/.bin/eslint assetsSource/js/*
