name: PHP Test Suite

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer install --no-interaction --no-ansi --no-suggest --no-progress --no-dev --optimize-autoloader

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
